### ISSUE TITLE
Allow injecting values into a job

### ISSUE THREAD

**Issue by jawher** [bazooka-ci/bazooka#129]
Such values can range from:

* Commonly used values across many builds, to avoid repeating them in every build descriptor file
* Sensitive data (server passwords, etc.) which can't be shared in the build descriptor file

Injecting values should be configurable on a global basis (into every job) or on a job basis.

Finally, these values should be exposed as environment variables at a minimum, possibly as files to be mounted on the build docker image

**Comment by jawher** [comment]
UI suggestions:

CLI:

```
bzk job start bazooka-release master TAG=1.15 GO=1.4
```

It'll be tougher for the web ui: one way to do it is a simple list of key/value inputs, but if we wanted to expose a more contexual UI, a project will need to define somewhere (not in the `.bazooka.yml` file) the list of keys it expects.

**Comment by haklop** [comment]
For the web ui we can list the keys defined on the server-side configuration map (https://github.com/bazooka-ci/bazooka/pull/158).

All the values defined on the configuration map are exposed as environment variables.

This command override the default value of TAG and GO defined on the configuration map:

    bzk job start bazooka-release master TAG=1.15 GO=1.4

Required values are defined on the bazooka.yml and the job failed if there are missing values.
