### ISSUE TITLE
Line number issue in Web 

### ISSUE THREAD

**Issue by julienvey** [bazooka-ci/bazooka#215]
Multiple numbers on the same line
![image](https://cloud.githubusercontent.com/assets/455944/7570178/6ffc3328-f80e-11e4-9df1-421c4205fcfd.png)

DOM looks like this 
![image](https://cloud.githubusercontent.com/assets/455944/7570188/8c08a4a2-f80e-11e4-94df-bd60ec62b477.png)

**Comment by jawher** [comment]
Got a fix, but I'll wait for #216 to be merged before to avoid conflicts.
