### ISSUE TITLE
404 on GET <server_url>/css/bootstrap.css.map

### ISSUE THREAD

**Issue by julienvey** [bazooka-ci/bazooka#245]

**Comment by haklop** [comment]
For me it's not an issue. It's only when opening Chrome debugger (and Firefox ?) on a page where there is a minified javascript or css whith a comment `sourceMappingURL=`.

*.map are helpers for debugging minified javascript or css.

You can enable/disable it on the chrome debugger settings:
![sourcemaps](https://cloud.githubusercontent.com/assets/4128/7680201/9c18849c-fd64-11e4-8dd8-fa1d38aab06c.png)

**Comment by julienvey** [comment]
Ok, thanks for the info
